// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzyqphDasC6dtg0kkFijgs54cwWkb-0Q',
    appId: '1:795938948017:web:3b3944e61018f8ac6db390',
    messagingSenderId: '795938948017',
    projectId: 'holbegram-b64b1',
    authDomain: 'holbegram-b64b1.firebaseapp.com',
    storageBucket: 'holbegram-b64b1.firebasestorage.app',
    measurementId: 'G-WPWBE4YMYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQxWIGU9zB4hTXkCxXFnLzTVIGcfEGKU4',
    appId: '1:795938948017:android:7c20cb8d43e407276db390',
    messagingSenderId: '795938948017',
    projectId: 'holbegram-b64b1',
    storageBucket: 'holbegram-b64b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXmp9lyDb4sN3eRJ5yaZTDaXZW5HIcx1g',
    appId: '1:795938948017:ios:714ffe09bbcb43fd6db390',
    messagingSenderId: '795938948017',
    projectId: 'holbegram-b64b1',
    storageBucket: 'holbegram-b64b1.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXmp9lyDb4sN3eRJ5yaZTDaXZW5HIcx1g',
    appId: '1:795938948017:ios:714ffe09bbcb43fd6db390',
    messagingSenderId: '795938948017',
    projectId: 'holbegram-b64b1',
    storageBucket: 'holbegram-b64b1.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzyqphDasC6dtg0kkFijgs54cwWkb-0Q',
    appId: '1:795938948017:web:4e5e12a6d6a11bdb6db390',
    messagingSenderId: '795938948017',
    projectId: 'holbegram-b64b1',
    authDomain: 'holbegram-b64b1.firebaseapp.com',
    storageBucket: 'holbegram-b64b1.firebasestorage.app',
    measurementId: 'G-7ZHGHV6QCZ',
  );
}
